version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # Autoreloads the server on code change
    command: /app/.venv/bin/python -m uvicorn api.index:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app/api
      - ./src_py:/app/src_py
      - ./assets:/app/assets
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      # local 8080 to nginx 80.
      # 8080 to avoid needing sudo and conflicts with local services.
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
